### ISSUE TITLE
svg files aren't rendered when $frontType / $backType is "image"

### ISSUE THREAD

**Issue by xlf1024** [xlf1024/anycardgame_serverbased#1]
### Background:
with `$...Type == "image" `(default), svg `image` elements are used for display instead of an `<iframe>` nested into `<foreignObject>`.
According to MDN, svg files should work in `<image>` the same as e.g. pngs, which work fine, so it shouldn't be an issue with how the files are loaded.
I guess, it's a) a browser bug or b) some security restriction, either related with the uncommon combination of `<image>` and `blob:` urls.
### TODO: 
- [ ] create a reduced test case
- [ ] test in other browsers
- [ ] research b)
- if a):
  - [ ] file bugs
- if b):
  - [ ] find and implement attributes (maybe csp, etc) to lift the restrictions, and/or switch to `data:` urls, if they work better

### workaround:
set `$...Type` to `html` for svg faces, too thus rendering them in an `<iframe>`. Caveat: click area is the bounding rectangle, so currently unsuitable for e.g. hexagonal tiles.

**Comment by xlf1024** [comment]
Fix was to set the mime type when creating the blob.
